// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6guUICdezCId19nX-tu0-yVMyCP_zvNI',
    appId: '1:1039020278532:web:17bd6bdd7a2b2bbb870651',
    messagingSenderId: '1039020278532',
    projectId: 'elaundry-494ce',
    authDomain: 'elaundry-494ce.firebaseapp.com',
    databaseURL: 'https://elaundry-494ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elaundry-494ce.firebasestorage.app',
    measurementId: 'G-JQDBXPWC5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8UKId-zhLJRolx_DwY__XyO0sD7k9jI',
    appId: '1:1039020278532:android:07e5a5558db07cb8870651',
    messagingSenderId: '1039020278532',
    projectId: 'elaundry-494ce',
    databaseURL: 'https://elaundry-494ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elaundry-494ce.firebasestorage.app',
  );
}
